# Generated by Django 5.2.17 on 2026-09-14 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hard', 'Hard Skills'), ('soft', 'Soft Skills')], default='hard', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('proficiency', models.IntegerField(default=80)),
            ],
        ),
    ]
