# Generated by Django 5.2.17 on 2026-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
